### ISSUE TITLE
Is it ready for production?

### ISSUE THREAD

**Issue by blacksmoke26** [sufitman/yii-react-gridview#1]
I would like to use in my current project. So my question is that it's still active and production ready?

Another noob question that it it works with Bootstrap 4? Because my current design based on is Bootstrap 4.

Thank you!

**Comment by sufitman** [comment]
Hi! 
I'm pretty sure you can use it in your project. As for its production-ready status - it's not covered with tests yet. Tests are planned in further releases

> Another noob question that it it works with Bootstrap 4?

Sure, you can wrap it with bootstrap 4 classes (if it differs from classes of bootstrap 3) by setting className prop in tableOptions or whateverOptions (see README).

**Comment by blacksmoke26** [comment]
Thank You!
